---
sudo: required
language: python
python: "2.7"
services:
  - docker
env:
  - distribution: centos
    version: 7
    jenkins_version: 2.89.3
  - distribution: centos
    version: 6
    jenkins_version: 2.73.3
  - distribution: debian
    version: jessie
    jenkins_version: 2.89.3
  - distribution: ubuntu
    version: artful
    jenkins_version: 2.60.3
  - distribution: ubuntu
    version: xenial
    jenkins_version: 2.73.3
  - distribution: ubuntu
    version: trusty
    jenkins_version: 2.89.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pip libssl-dev
  - pip install docker-py
  - /usr/bin/env
install:
  - pip install molecule==2.5.0
  - pip install ansible==2.4.0
  - ansible --version
  - molecule --version
  - py.test --version

script:
  - molecule test
