---
sudo: required
language: python
python: "2.7"
services:
  - docker
env:
  - distribution: centos
    version: 7
    jenkins_stable: True
    jenkins_version: latest
    jenkins_test_version: 2.107.3
  - distribution: centos
    version: 7
    jenkins_stable: False
    jenkins_version: latest
    jenkins_test_version: 2.124
  - distribution: ubuntu
    version: artful
    jenkins_stable: True
    jenkins_version: 2.73.3
    jenkins_test_version: 2.73.3
  - distribution: ubuntu
    version: artful
    jenkins_stable: False
    jenkins_version: 2.99
    jenkins_test_version: 2.99
  - distribution: ubuntu
    version: xenial
    jenkins_stable: True
    jenkins_version: latest
    jenkins_test_version: 2.107.3
  - distribution: ubuntu
    version: xenial
    jenkins_stable: False
    jenkins_version: 2.102
    jenkins_test_version: 2.102
  - distribution: ubuntu
    version: trusty
    jenkins_stable: True
    jenkins_version: latest
    jenkins_test_version: 2.107.3
  - distribution: ubuntu
    version: trusty
    jenkins_stable: False
    jenkins_version: latest
    jenkins_test_version: 2.124
  - distribution: debian
    version: 8
    jenkins_stable: True
    jenkins_version: latest
    jenkins_test_version: 2.107.3
  - distribution: debian
    version: 8
    jenkins_stable: False
    jenkins_version: latest
    jenkins_test_version: 2.124
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq -y python-pip libssl-dev
  - pip install docker-py
  - pip install ansible==2.4.0
  - pip install molecule==2.5.0
before_script:
  - ansible --version
  - molecule --version
  - py.test --version
  - echo 'Environment list:'
  - /usr/bin/env
script:
  - molecule test
