---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/yamllint.yml
platforms:
  - name: "java-test-${distribution}-${version}"
    image: "${distribution}:${version}"
    privileged: 'true'
    groups:
      - test
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - dependency
    - syntax
    - destroy
    - create
    - prepare
    - converge
    - verify
    - idempotence
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
