---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/yamllint.yml
platforms:
  - name: "jenkins-test-${distribution}-${version}"
    image: "${distribution}:${version}"
    privileged: True
    groups:
      - test
      - java
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
