---
- hosts: test
  become: true
  remote_user: root
  roles:
    - DovnarAlexander.oracle-java
    - ansible-jenkins
  vars:
    jenkins_version: "{{ lookup('env','jenkins_version') }}"
    jenkins_stable: "{{ lookup('env','jenkins_stable') | bool }}"
    jenkins_users:
      -
        id: test-user
        email: test-user@gmail.com
        password: test-user
    jenkins_userpass_credentials:
      -
        id: test-credentials
        description: "For test"
        username: test-credentials-user
        password: test-credentials-password
    jenkins_secret_text_credentials:
      -
        id: test-text-credentials
        description: "For test"
        secret_text: test-text-credentials
    jenkins_ssh_credentials:
      -
        id: test-ssh-user
        username: test-ssh-user
        print: True
        description: "For test"
      -
        id: jenkins-local-slave
        username: jenkins
        local: True
        description: "For test"

    jenkins_nodes:
      -
        name: master
        type: master
        labels: master
        executors: 7
      -
        name: test-jnlp
        executors: 1
        labels: test-jnlp
        type: jnlp
        home_path: /home/jenkins
        description: 'test-jnlp'
      -
        name: test-ssh
        executors: 1
        labels: test-ssh
        type: ssh
        external_host: 127.0.0.1
        credentials: jenkins-local-slave
        home_path: '/var/lib/jenkins'
        description: 'test-ssh'
        environment:
          FOO: bar
          BAR: foo
