---
- name: Prepare
  hosts: all
  gather_facts: False
  pre_tasks:
    - name: Install Python.
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)
      changed_when: False
      ignore_errors: yes
